### ISSUE TITLE
Have option to not hide deleted events

### ISSUE THREAD

**Issue by Miepee** [ajbura/cinny#1340] opened 2023-07-14 21:27 UTC
### Describe the problem

Other clients have the ability to show that events were deleted, which helps in some scenarios (i.e trying to make sense of a conversation after a person has deleted some messages themselves)

### Describe the solution you'd like

Have an option to hide/show deleted events

**Comment by kfiven** [comment] 2023-10-19 10:38
Duplicate of #1268

**Closed as completed by kfiven** 2023-10-19 10:38 UTC
