### ISSUE TITLE
Can't install on a subdir anymore

### ISSUE THREAD

**Issue by Salamandar** [ajbura/cinny#1843] opened 2024-07-25 16:23 UTC
### Describe the bug

The original issue was fixed here: https://github.com/cinnyapp/cinny/pull/1094/files

But is was broken again here : https://github.com/cinnyapp/cinny/blob/44161c4157dccac383025825f5fd4d7f4620ea67/build.config.ts

Would it be possible (not sure it's compatible with url nav though) to put back `base = ""` to allow installation in a subdir? Thanks !

### Reproduction

* Install cinny behind a `location /cinny/` in nginx
* index.html contains absolute paths to `/assets` that aren't prefixed by `/cinny/`

### Expected behavior

Pages load

### Platform and versions

```shell
Cinny version : v4.0
```

**Comment by ajbura** [comment] 2024-07-25 16:30
App requires base url ahead of build so app can locate it's config file with base url, otherwise config file need to be placed at the root of domain which might not be possible and can be complicated with file name collision. also we can't put relative path for assets as app now have url navigation and relative path will resolved relative to current url which is not always app base url

**Comment by ajbura** [comment] 2024-07-25 16:38
To deploy it on subdir you have to build the app after changing base in `build.confg.ts` file

**Comment by kfiven** [comment] 2024-08-04 05:06
Closing as explained above. To deploy on subdir app needs to be rebuilt after changing the build.config.

**Closed as completed by kfiven** 2024-08-04 05:06 UTC

**Comment by Salamandar** [comment] 2024-08-09 12:17
Considering Cinny requires ~5GB of RAM to build (See https://github.com/vitejs/vite/issues/2433), we can't consider rebuilding cinny on things like raspberry pis…

**Comment by kfiven** [comment] 2024-08-09 13:53
but the issue is we can't provide a prebuilt tar or something because the subfir for each people could be different, so there do not seems to be any other option here.

**Comment by kfiven** [comment] 2024-08-09 13:54
seems a downside of having the URL routing now, but it is what it is.

**Comment by oleole39** [comment] 2024-11-02 01:22
> also we can't put relative path for assets as app now have url navigation and relative path will resolved relative to current url which is not always app base url

Do you mean we could not have default `build.config.ts` as:
```
export default {
  base: './',
};
```
instead of :
```
export default {
  base: '/',
};
```

I don't really understand the URL navigation point mentioned here, but I've done a quick test modifying [path from absolute to relative in 2 files](https://github.com/YunoHost-Apps/cinny_ynh/pull/66#issuecomment-2444597718) of the prebuilt release archive and it seemed to work.

**Comment by oleole39** [comment] 2024-11-02 23:43
> I've done a quick test modifying [path from absolute to relative in 2 files](https://github.com/YunoHost-Apps/cinny_ynh/pull/66#issuecomment-2444597718) of the prebuilt release archive and it seemed to work.

Hmm actually not, forget it.
