### ISSUE TITLE
Linkify #room:homeserver.xyz messages

### ISSUE THREAD

**Issue by jedahan** [ajbura/cinny#1138] opened 2023-02-23 18:59 UTC
### Describe the problem

I want to be able to click on text when someone shares a room as plain text message like `#room:homeserver.tld`

### Describe the solution you'd like

Currently, messages will link the domain, but not the room:

![Screenshot 2023-02-23 at 1 54 22 PM](https://user-images.githubusercontent.com/32407/221003321-51bb4c67-ae90-40c8-8c28-ef3b32ed98d6.png)

it would be nice to link the room

![Screenshot 2023-02-23 at 1 54 55 PM](https://user-images.githubusercontent.com/32407/221003461-008a47e5-1261-4f39-a7e2-1e0dab7dd009.png)

which i would expect to link a la https://matrix.to/#/#infra:woodbine.nyc

**Comment by kfiven** [comment] 2023-02-23 21:01
Duplicate of #778

**Closed as completed by kfiven** 2023-02-23 21:01 UTC
