### ISSUE TITLE
Option to hide sidebar

### ISSUE THREAD

**Issue by nonl4331** [ajbura/cinny#1035] opened 2022-12-21 05:45 UTC
### Describe the problem

I have noticed that the navigation bar takes up a significant amount of screen real estate and can be distracting while I'm trying to focus on the chat conversation. 

### Describe the solution you'd like

I would like an option to close the navigation bar and simply use the existing keybind (ctrl+k) for the search bar to navigate to different chats and channels.

This would allow users to quickly and easily navigate through their chats without having to constantly switch between the navigation bar and the conversation window. It would also make the interface less cluttered and allow users to focus more on the conversation at hand.

**Comment by nonl4331** [comment] 2022-12-21 08:09
#1036 appears to have a working implementation.

**Comment by duarm** [comment] 2022-12-21 16:56
duplicate of #803 it seems

**Comment by ajbura** [comment] 2022-12-22 03:13
duplicate as above

**Closed as completed by ajbura** 2022-12-22 03:13 UTC
