### ISSUE TITLE
Disable Read Receipts / Typing Indicators when Disabled on the Homeserver

### ISSUE THREAD

**Issue by snit-guckfung** [ajbura/cinny#1976] opened 2024-09-24 02:20 UTC
### Describe the bug

My homeserver turned off presence, read receipts, and typing indicators, so I shouldn't be seeing these whatsoever. However, if someone sends a message or reaction, I still see "X is following the conversation" at the bottom, and if I start typing, I'm shown as typing on the sidebar.

### Reproduction

1. Log into a server that has read receipts and typing indicators turned off

READ RECEIPTS:
2. Receive a message or reaction
3. The "X is following the conversation" text should appear

TYPING INDICATOR:
2. Type a message
3. Look at your profile on the sidebar (it should show as typing)

### Expected behavior

Considering these were turned off at the homeserver level, I would've expected these to just not show up. If its possible, I'd like to see these disabled for such homeservers, or otherwise an option provided for me to turn these off within the client.

### Platform and versions

```shell
1. OS: Arch Linux
2. Browser: Mozilla Firefox 130.0.1
3. Cinny version: Cinny v4.2.1 (cinny.isekai.rocks)
4. Homeserver: isekai.rocks (conduwuit 0.4.6, if that matters)
```

**Comment by kfiven** [comment] 2024-09-27 11:50
duplicate of #785 & #240

**Closed as not planned by kfiven** 2024-09-27 11:50 UTC

**Comment by ajbura** [comment] 2025-02-13 04:06
@throwaway-lmao can you please provide the [capabilities](https://spec.matrix.org/latest/client-server-api/#get_matrixclientv3capabilities) response of your homeserver, to know how the client found that these features are disabled on homeserver level.

**Comment by snit-guckfung** [comment] 2025-02-13 18:11
Running
```sh
curl -H 'Authorization: Bearer <token>' https://matrix.isekai.rocks/_matrix/client/v3/capabilities
```
gave me
```json
{
  "capabilities": {
    "m.change_password": { "enabled": true },
    "m.room_versions": {
      "default": "10",
      "available": {
        "10": "stable",
        "11": "stable",
        "2": "unstable",
        "3": "unstable",
        "4": "unstable",
        "5": "unstable",
        "6": "stable",
        "7": "stable",
        "8": "stable",
        "9": "stable"
      }
    },
    "m.set_displayname": { "enabled": true },
    "m.set_avatar_url": { "enabled": true },
    "m.3pid_changes": { "enabled": false }
  }
}
```
