### ISSUE TITLE
Docker - config.json is ignored

### ISSUE THREAD

**Issue by daedric7** [ajbura/cinny#1314] opened 2023-06-26 00:09 UTC
### Describe the bug

I'm using Cinny with docker (via docker compose).

config.json is mounted inside the container in /app/config.json.

Yet, aparently it's being ignored, the defaults always show up.

### Reproduction

**docker-compose.yaml:**

```
version: '3.3'
services:
    cinny:
        image: 'ghcr.io/cinnyapp/cinny:latest'
        restart: always
        volumes:
            - ./config.json:/app/config.json
```

**config.json:**

```
{
  "defaultHomeserver": 0,
  "homeserverList": [
    "myserver.com"
  ],
  "allowCustomHomeservers": false
}
```

### Expected behavior

Only one server available on the server selection ,without option to use custom server.

### Platform and versions

```shell
Oracle Free Arm, official docker.
```

**Comment by kfiven** [comment] 2023-06-26 02:33
Have you seen [these](https://github.com/search?q=cinny+config.json+language%3Ayaml&type=code)? I haven't tried what you are doing but some folks were able to achieve that sucessfully.

**Comment by daedric7** [comment] 2023-06-26 08:07
Weirdly, i arrived on job today, opened the same webpage, and config.json was loaded correctly.

I'll investigate further at home, see if it's a cookie or something still cached.

**Comment by sbug0** [comment] 2023-07-20 22:27
I have the same issue, but I'm not using docker but rather just unpacking the tarball in the weboot

**Comment by Domoel** [comment] 2023-08-01 21:48
thank you sir! You helped me to figure out how the config.json is working and to which path one has to mount it. :-)

**Comment by merrkry** [comment] 2024-05-02 07:37
Reproduced here on Archlinux.

It's strange that firefox have the site with default settings but chromium works as expected.

**Comment by Curious-r** [comment] 2024-06-17 20:50
You can simplely try to shift+F5 on chrome

**Comment by kfiven** [comment] 2024-09-14 04:07
Closing as seems to be resolved.

**Closed as not planned by kfiven** 2024-09-14 04:07 UTC
