### ISSUE TITLE
Paste images from clipboard

### ISSUE THREAD

**Issue by Dlurak** [ajbura/cinny#1989] opened 2024-10-03 12:47 UTC
### Describe the problem

Currently it is not possible to paste an image from the clipboard into cinny

### Describe the solution you'd like

Pasting an image into Cinny would trigger the image upload dialog.

### Additional context

I'm using Linux and Wayland

**Comment by kfiven** [comment] 2024-10-13 20:25
Are you talking about desktop app?

**Comment by Dlurak** [comment] 2024-10-13 20:30
Yes, the desktop App on Linux and Wayland

**Comment by kfiven** [comment] 2024-10-13 20:32
Thanks for quick response. This is duplicate of https://github.com/cinnyapp/cinny-desktop/issues/69

**Closed as not planned** 2024-10-13 20:32 UTC
