### ISSUE TITLE
Add a search bar to the sticker picker

### ISSUE THREAD

**Issue by tux93** [ajbura/cinny#1026] opened 2022-12-19 11:47 UTC
### Describe the problem

Currently there is no way to search for a particular sticker, which can become a problem when stickers become more widespread and one adds a lot of stickerpacks.

### Describe the solution you'd like

Add a search bar to the sticker picker to enable users to (wildcard) search for stickers by their shortcode, similar to the search in the emoji picker.

**Comment by kfiven** [comment] 2022-12-19 11:58
duplicate of #741

**Closed as completed by kfiven** 2022-12-19 11:58 UTC
