### ISSUE TITLE
Add embeds/preview links like in Element

### ISSUE THREAD

**Issue by TheDragonary** [ajbura/cinny#1428] opened 2023-09-15 15:50 UTC
### Describe the problem

Element is able to show embeds for website links, youtube links, tenor gif links, etc, but Cinny is unable to do this.

### Describe the solution you'd like

I want Cinny to be able to preview/embed links like how Element or Discord does it.

**Comment by kfiven** [comment] 2023-09-15 21:06
Duplicate of #284

**Closed as completed by kfiven** 2023-09-15 21:06 UTC
