### ISSUE TITLE
Keyword notifications are not marked as read automatically.

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#238] opened 2022-01-16 04:26 UTC
#### To Reproduce
1. Set a keyword notification for a chat (in element.)
2. Get a notification.
3. Click on the chat with the notification.
4. It will say "1" forever, unless you manually mark the chat as read.

#### Expected behavior
I expected that the notification would go away when I clicked on the chat.

#### Screenshots
Already marked it as read :p

#### Desktop (please complete the following information):
 - OS: Arch Linux
 - Browser: Librewolf
 - Version: 1.6.1

**Comment by kfiven** [comment] 2022-01-22 15:21
This behaviour is not limited to keyword notifications, it happens for all notifications and intentional.

Ajbura explained [here](https://github.com/ajbura/cinny/issues/184#issuecomment-993635359) why it works like this.

**Comment by viasux** [comment] 2022-01-23 06:52
> This behaviour is not limited to keyword notifications, it happens for all notifications and intentional.
> 
> Ajbura explained [here](https://github.com/ajbura/cinny/issues/184#issuecomment-993635359) why it works like this.

My issue is different. It doesn't even show where the keyword notification is, so since that's how marking as read works, you can't see how far to scroll (to my knowledge, going off memory)

**Comment by kfiven** [comment] 2022-01-23 07:01
Are you looking for something similar for keywords like #235 ?

**Comment by viasux** [comment] 2022-02-18 14:34
> Are you looking for something similar for keywords like #235 ?

I think keywords function the same as mentions, just cinny doesn't recognize them as mentions, so it never clears the notification.

**Comment by ajbura** [comment] 2022-02-18 14:47
It’s intended behaviour as discussed in #184. Marking as read is done when user explicitly does it.

**Comment by viasux** [comment] 2022-02-18 14:49
> It’s intended behaviour as discussed in #184. Marking as read is done when user explicitly does it.

In my experience, scrolling up to the keyword (which is not displayed or visible where you were mentioned) and then back down to the bottom does not mark the chat as read / the keyword as being seen.

**Comment by ajbura** [comment] 2022-02-18 14:57
Mark as read is only done, a) when you click the button or b) scroll to `New Messages` divider and then come to bottom. Cinny is only aware of new message divider (the place upto which you read last time) because of read receipts but there’s no easy way know where someone got pinged, so any kind of notification is marked read by earlier two ways.

**Comment by ajbura** [comment] 2022-02-18 15:05
And even if we get the place of ping, we can only mark room read from last unread to upto that ping which will be wrong because user only read messages below the ping. (Unfortunately that’s how read receipts works).

**Comment by ajbura** [comment] 2022-05-28 13:34
Closing as there’s little we can do to solve the issue.

**Closed as completed by ajbura** 2022-05-28 13:34 UTC
