### ISSUE TITLE
Make collapsed state of categories in room-list panel persistent per view

### ISSUE THREAD

**Issue by williamkray** [ajbura/cinny#766] opened 2022-08-18 16:59 UTC
### Describe the problem

Currently, if I visit the Home view (which shows two categories: "spaces" and "rooms") and collapse the "spaces" category, then navigate to another view (perhaps "people"), and then return to the Home view, the "spaces" category is re-expanded.

This behavior is consistent with any category, so long as the views switched between do not have the same category. For example, if I collapse the "spaces" category in the Home view, then switch to a space which includes subspaces and does not have categorization of subspaces enabled, then the space view also includes a "spaces" category, and it will remain collapsed. This will persist until the view is changed to one which does not include a "spaces" category, and then subsequent views of rooms that _do_ have a "spaces" category will again be expanded.

This is most easily testable by visiting Home, collapsing the "rooms" category. Then, view any space that has rooms. Then, switch to the "people" view (which does not have a "rooms" category), and then go to either Home or any space.

### Describe the solution you'd like

I would like the collapsed/expanded status of these categories to persist in my session within each view... for example, if I have a space that contains both "rooms" and "people" categories, and I collapse the "rooms" section, I want that setting to persist within that space, but not affect the "rooms" section of other spaces or the Home meta-space.

Similarly, if I collapse the "spaces" category within the Home meta-space, I want that collapsed state to be persisted.

**Comment by ajbura** [comment] 2022-08-18 17:04
duplicate of #607

**Closed as not planned by ajbura** 2022-08-18 17:04 UTC
