### ISSUE TITLE
Uploading many custom emoji as once.

### ISSUE THREAD

**Issue by GamePlayer-8** [ajbura/cinny#1147] opened 2023-03-05 09:49 UTC
### Describe the problem

I have many custom emojis and I need to upload them one by one.

### Describe the solution you'd like

I would like to upload all of them at once by having an option to select multiple emojis from a folder.

**Comment by kfiven** [comment] 2023-03-05 10:17
duplicate of #940

**Closed as completed by kfiven** 2023-03-05 10:17 UTC
