### ISSUE TITLE
There is no way to recover the password.

### ISSUE THREAD

**Issue by PrincessKaya** [ajbura/cinny#987] opened 2022-11-20 18:55 UTC
### Describe the bug

When logging in by email to an existing account, there is no way to recover the password if it is forgotten. 

### Platform and versions

```shell
1. OS Windows 10
2. Browser: Сhrome last version 107.0.5304.107
3. Cinny version: 2.2.2
4. Matrix homeserver: matrix.org
```

**Comment by kfiven** [comment] 2022-11-21 00:52
Duplicate of #26

**Closed as completed by kfiven** 2022-11-21 00:52 UTC
