### ISSUE TITLE
👎 Cinny is deceiving users. There is no channel classification function

### ISSUE THREAD

**Issue by Pantyhose-X** [ajbura/cinny#647] opened 2022-06-25 02:16 UTC
### Describe the problem

cinny is tricking the user, there is no channel classification function at all. They just put the symbol # in front of the group name
👎 -100

### Describe the solution you'd like

cinny is tricking the user, there is no channel classification function at all. They just put the symbol # in front of the group name

**Comment by ajbura** [comment] 2022-06-25 03:20
duplicate of #44

**Closed as not planned by ajbura** 2022-06-25 03:20 UTC

**Comment by tezlm** [comment] 2022-08-12 10:55
its official `type` in `m.room.create` no longer exists
