### ISSUE TITLE
Allow timestamps to be shown in 24-hour format

### ISSUE THREAD

**Issue by jivanpal** [ajbura/cinny#1333] opened 2023-07-09 01:19 UTC
### Describe the problem

Currently, timestamps are of the form "HH:SS AM/PM". I would like an option to toggle this to 24-hour times of the format "HH:SS" with HH ranging between 0 and 23.

Additionally, common convention in the West is for 12-hour times to never be written with a leading zero in the hour, but Cinny does present one, e.g. 3am is displayed as "03:00 AM" rather than the "3:00 AM" that I would expect. Perhaps conventions differ internationally, but it might be worth also changing the 12-hour format to this in addition to adding the 24-hour option.

### Describe the solution you'd like

As above: I would like an option to toggle this to 24-hour times of the format "HH:SS" with HH ranging between 0 and 23.

**Comment by kfiven** [comment] 2023-07-09 02:45
Duplicate of #60

**Closed as completed by kfiven** 2023-07-09 02:45 UTC
