### ISSUE TITLE
Enlarged emoji if sent by itself

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#244] opened 2022-01-20 18:01 UTC
#### Is your feature request related to a problem? Please describe.
An enlarged version of an emoji should be sent if the emoji is the only content in the message. Currently, the emoji by itself with no text looks a bit weird.
![image](https://user-images.githubusercontent.com/47131867/150395353-cbacc04e-df0b-45af-b825-d3d1667cb939.png)

#### Additional context
This is what element does (I think that element makes it a fair bit bigger than would make sense in cinny, but I still think that cinny should enlarge emoji by itself a little)
I think 1.5-2x the size would make sense in cinny.
![image](https://user-images.githubusercontent.com/47131867/150395501-731b011b-bed6-40cf-931f-15af830b944c.png)

**Comment by kfiven** [comment] 2022-01-21 03:03
Duplicate of #204

**Closed as completed by kfiven** 2022-01-21 03:03 UTC

**Comment by kfiven** [comment] 2022-01-21 03:04
It's done in dev branch so will land in stable in next release.
