### ISSUE TITLE
Feat: Option for 24-hour and 12-hour toggle

### ISSUE THREAD

**Issue by kdh8219** [ajbura/cinny#1648] opened 2024-03-01 16:58 UTC
### Describe the problem

24-Hour is cool
Makes it more intuitive to see the time at 0 and 12 o'clock

### Describe the solution you'd like

make an option or use system option for time fromat

### Additional context

https://github.com/cinnyapp/cinny/blob/689adde8ae148d2de76bab0d11d7e0e8f35b7439/src/app/utils/time.ts#L12

**Comment by kfiven** [comment] 2024-03-02 12:04
duplicate of #60

**Closed as completed by kfiven** 2024-03-02 12:04 UTC
