### ISSUE TITLE
Message edit crash

### ISSUE THREAD

**Issue by greentore** [ajbura/cinny#1046] opened 2022-12-30 22:26 UTC
### Describe the bug

The app crashes when you try to edit a message containing an unknown shortcode.

### Reproduction

1. Send a message containing `:aa:`
2. Try to edit it

### Platform and versions

```shell
1. OS: Windows 10
2. Browser: Chromium 108.0.5359.125
3. Cinny: v2.2.2 (local dev server)
```

### Additional context

The app is checking `state.emojis` property which isn't set during edit parsing.

**Comment by kfiven** [comment] 2022-12-31 04:00
Duplicate of #955

**Closed as completed by kfiven** 2022-12-31 04:00 UTC
