### ISSUE TITLE
"Jump to Mention" instead of "Jump to unread" when mentioned

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#935] opened 2022-10-18 00:56 UTC
### Describe the problem

When I get mentioned in a large room, I just want to see where i was mentioned, not thousands of messages. A button to jump to the mention would be tremendously useful.

### Describe the solution you'd like

A "Jump to Mention" button near or replacing the "Jump to Unread" button

### Alternatives considered

scrolling though lots of text

**Comment by kfiven** [comment] 2022-10-18 02:24
Duplicate of #235

**Closed as not planned by kfiven** 2022-10-18 02:24 UTC
