### ISSUE TITLE
web page should handle the 'back' action

### ISSUE THREAD

**Issue by LiAlH4qwq** [ajbura/cinny#661] opened 2022-07-04 08:18 UTC
### Describe the problem

in current version, 'back' action(back key on the phone or back button on the browser will only cause cinny exited

### Describe the solution you'd like

its better to handle the 'back' action as telegram web does to provide a more user friendly experience

### Alternatives considered

none currently

### Additional context

N.A.

**Comment by kfiven** [comment] 2022-07-04 11:00
duplicate of #70

**Closed as not planned by kfiven** 2022-07-04 11:00 UTC
