### ISSUE TITLE
Can't paste image from clipboard.

### ISSUE THREAD

**Issue by BlitDev** [ajbura/cinny#952] opened 2022-10-28 11:08 UTC
### Describe the bug

For example, I take a screenshot with Flameshot, try to paste with Ctrl + V, but nothing happens. Although it works in Nheko, Element, SchildiChat and all other clients.

### Expected behavior
Screenshot pasted as attachment.

### Platform and versions

```shell
1. OS: Arch Linux (latest ver.)
2. Cinny Version: 2.2.2-1 (from AUR)
3. Matrix homerserver: inex.rocks (matrix.inex.rocks)
```

**Comment by ajbura** [comment] 2022-10-28 12:40
Duplicate of https://github.com/cinnyapp/cinny-desktop/issues/69

**Closed as not planned by ajbura** 2022-10-28 12:40 UTC
