### ISSUE TITLE
Switching between rooms and DMs opens the first chat on mobile

### ISSUE THREAD

**Issue by notramo** [ajbura/cinny#1126] opened 2023-02-18 11:29 UTC
### Describe the bug

Switching between rooms and DMs opens the first chat on narrow screen.

### Expected behavior

Optimal UX would be to show the chat list.

### Platform and versions

```shell
All platforms affected.
```

### Additional context

Opening the first chat is useful on wide screens, because both the chat window and the chat list are displayed. But it's a drawback on mobile, because only one of the aforementioned two fits the screen.

**Comment by LinuxinaBit** [comment] 2023-02-27 02:40
Oh, I’ve noticed this, I could see how someone could want the current behavior though, as the last chat opened in a room would be what is opened when you click on it.
Maybe a toggle in settings is best.
I personally would love to see a list of rooms when a Matrix Space/group category is opened by default.

**Comment by kfiven** [comment] 2023-10-13 23:35
duplicate of #1376

**Closed as completed by kfiven** 2023-10-13 23:35 UTC
