### ISSUE TITLE
[Desktop] Open in new tab does nothing

### ISSUE THREAD

**Issue by mahdi1234** [ajbura/cinny#657] opened 2022-06-28 14:51 UTC
### Describe the bug

With desktop version click on "Open in new tab" icon for any image --> nothing happens.

### Platform and versions

```shell
cinny_2.0.4_amd64.AppImage on Gentoo linux
```

**Comment by kdormer** [comment] 2022-06-29 15:38
Can confirm, I'm getting the same issue on Arch Linux with the desktop version.

**Comment by kfiven** [comment] 2022-06-29 15:45
duplicate of #534

**Closed as not planned by kfiven** 2022-06-29 15:45 UTC
