### ISSUE TITLE
Reply in Thread

### ISSUE THREAD

**Issue by ghost** [ajbura/cinny#1773] opened 2024-06-11 05:53 UTC
### Describe the problem

#ROOMS  Cinny
##Cinny issus  
> Cinny issus. is ROOMS Cinny. "Reply in Thread"
---

Discord channel bridge to Cinny Reply in Thread.

### Describe the solution you'd like

like (Element) Reply in Thread 

### Additional context

#ROOMS **AA Testing  invites**
##AAA test enc 
> AAA test enc is ROOMS AA Testing  invites. "Reply in Thread"

##Anime & Manga
> Anime & Manga is ROOMS AA Testing  invites. "Reply in Thread"

![Screenshot_20240611-131314](https://github.com/cinnyapp/cinny/assets/169121286/39235b9b-55a7-4bb1-84e3-b25ccfbe672d)

**Comment by kfiven** [comment] 2024-06-11 13:42
Duplicate of #257

**Closed as not planned by kfiven** 2024-06-11 13:42 UTC
