### ISSUE TITLE
Add Import Emojis/Stickers from zip.

### ISSUE THREAD

**Issue by ghost** [ajbura/cinny#1968] opened 2024-09-23 17:27 UTC
### Describe the problem

When I want to create a stickers/emojis pack, when the number of stickers/emojis is large, it takes a lot of time to import those emojis/stickers and it takes my time.

### Describe the solution you'd like

In emojis section, when we have created a pack, there should be an option to import the emoji/stickers from a zip file.

**Comment by kfiven** [comment] 2024-09-23 22:34
duplicate of #940

**Closed as not planned by kfiven** 2024-09-23 22:34 UTC
