### ISSUE TITLE
Sticker picker menu search box and shortcut

### ISSUE THREAD

**Issue by nrgill28** [ajbura/cinny#1189] opened 2023-04-06 04:33 UTC
### Describe the problem

With emojis, I typically type out the `:emoji_name:` because it's faster for me if I know exactly which one I want. If I don't know exactly which one I want I can also search for it using the search box in the emoji picker menu. Stickers however have neither of these shortcut features, making you click to open the picker menu and scroll to find the sticker you want.

### Describe the solution you'd like

It would be great if the sticker picker menu also had a search box at the top, like the emoji picker does.

Also, because typing out a `:sticker_name:` into the message box does not make sense, a keyboard shortcut (e.g. Discord uses Ctrl+S) which opens the sticker picker menu and focuses the search box so you can type the sticker name and hit enter to send it would be a great solution for sending stickers entirely with the keyboard.

**Comment by kfiven** [comment] 2023-04-06 08:18
Duplicate of #741 ?

**Comment by lilyispuppy** [comment] 2023-06-05 21:38
As far as I know there is no shortcut for the emoji panel either. We should add the sticker and emoji shortcutst together. `ctrl + s` and `ctrl + e` respectively

**Comment by kfiven** [comment] 2024-09-14 04:00
Closing as duplicate above. For the keyboard shortcut see #219

**Closed as not planned by kfiven** 2024-09-14 04:00 UTC
Labels: accessibility, area: emojiboard
