### ISSUE TITLE
Image Preview

### ISSUE THREAD

**Issue by AvMavs** [ajbura/cinny#961] opened 2022-11-02 05:31 UTC
### Describe the problem

When I share an image link, it does not share an image preview like Discord does.

### Describe the solution you'd like

An image preview for an image link. 

Sharing [this](https://cdn.shopify.com/s/files/1/0058/4538/5314/files/LTT_Multi_Nep_Hoodie_Banner_WEB_1_2800x.png?v=1660954392) link should show a preview of the imahe as well

**Comment by tux93** [comment] 2022-12-09 15:25
URL previews would be nice but this is a duplicate of #284

**Comment by ajbura** [comment] 2024-07-26 17:17
closing as url previews has been added a while back.

**Closed as completed by ajbura** 2024-07-26 17:17 UTC
Labels: type: feature, area: timeline
