### ISSUE TITLE
Highlight notify messages

### ISSUE THREAD

**Issue by tranzystorekk** [ajbura/cinny#874] opened 2022-09-25 20:32 UTC
### Describe the problem

In some places, like irc bridges, special bot notification messages are sent that other clients highlight, e.g. Element:

![obraz](https://user-images.githubusercontent.com/5671049/192163834-38921251-15ac-4b5e-99bd-3fc5d2e6ecf6.png)

I don't know the exact nomenclature, but in cinny these are marked as `"msgtype": "m.notice"`, yet they are indistiunguishable form normal user messages.

### Describe the solution you'd like

I would like the messages described above to be possible to format/highlight in some way, maybe similar to what Element does.

**Comment by kfiven** [comment] 2022-09-26 02:43
Duplicate of #321

**Closed as not planned by kfiven** 2022-09-26 02:43 UTC
