### ISSUE TITLE
Focus Emoji `<Input/>` on modal open

### ISSUE THREAD

**Issue by jasikpark** [ajbura/cinny#229] opened 2022-01-05 20:15 UTC
#### Is your feature request related to a problem? Please describe.

When using the emoji picker, I usually want to immediately search for an emoji or [select from recently used emoji](https://github.com/ajbura/cinny/issues/194) 

#### Describe the solution you'd like

When ever the emoji picker modal is opened, I want the input to be cleared (or the text that is in there selected) and focused so I can immediately start typing

**Comment by kfiven** [comment] 2022-01-06 08:54
Duplicate of #62 ?

**Comment by jasikpark** [comment] 2022-01-10 19:20
looks like it!

**Comment by jasikpark** [comment] 2022-01-10 19:20
closing as a duplicate of #62

**Closed as completed** 2022-01-10 19:20 UTC
