### ISSUE TITLE
Video calls with screen share

### ISSUE THREAD

**Issue by yajo** [ajbura/cinny#1197] opened 2023-04-12 06:48 UTC
### Describe the problem

I can't do video-calls and share screen.

### Describe the solution you'd like

I'd love to be able to do video calls with Cinny.

### Alternatives considered

Web-based element is the only solution so far. Or pinning an old release where screen-sharing wasn't yet broken.

### Additional context

I've been struggling with Matrix to find a client that lets me do 1:1 video calls with screen sharing.

You'd say that Element does this, right? But I'm on Fedora Silverblue. This means that the preferred installation method for apps is Flatpak. And Element Inc. doesn't support anything but Ubuntu .deb packages, and at some point the feature got broken in the unofficial Flatpak build. Refs: https://github.com/vector-im/element-desktop/issues/656, https://github.com/vector-im/element-desktop/issues/657, https://github.com/flathub/im.riot.Riot/issues/334.

As I've been testing clients, I have to say Cinny is really awesome! I love it.

I also see that your main distribution packages for Linux are AppImage and Flatpak. Cool! That seems like a 21th century client finally! ❤️ 

Given the current situation in other clients, this would turn a killer feature for Cinny.

**Comment by axwnet** [comment] 2023-04-25 21:16
duplicate of https://github.com/cinnyapp/cinny/issues/528

**Closed as not planned** 2024-09-14 04:02 UTC
