### ISSUE TITLE
Add option to load and show room/space avatars in sidebars

### ISSUE THREAD

**Issue by ShadowJonathan** [ajbura/cinny#214] opened 2021-12-30 12:23 UTC
After a while of using matrix on Element, i'm more accustomed to recognising rooms by their avatar colours off in the sidebar.

Cinny currently does a bit away with this, and shows generic avatars;

![image](https://user-images.githubusercontent.com/22740616/147751620-0c26bfa0-9b7a-43c7-8d03-b7628ff43dbe.png)

While i understand the design choice, I'd also like to be able to see the room avatars of these rooms in an opt-in fashion.

**Comment by kfiven** [comment] 2022-01-21 04:08
duplicate of #107

**Closed as completed by kfiven** 2022-01-21 04:08 UTC
