### ISSUE TITLE
arm64 Linux Desktop app?

### ISSUE THREAD

**Issue by DUOLabs333** [ajbura/cinny#553] opened 2022-05-14 16:43 UTC
### Describe the problem

I want to try out Cinny Desktop, but it's not built for arm64.

### Describe the solution you'd like

Start building cinny-desktop for arm64.

**Comment by kfiven** [comment] 2022-05-15 07:11
duplicate of cinnyapp/cinny-desktop#62

**Closed as completed by kfiven** 2022-05-15 07:11 UTC

**Comment by DUOLabs333** [comment] 2022-05-15 11:02
No, because that refers to MacOS arm64. I'm referring to Linux arm64.

**Comment by kfiven** [comment] 2022-05-15 11:05
Just left a comment there, as someone also request one for windows in that issue.
