### ISSUE TITLE
Emoji settings menu crashes cinny

### ISSUE THREAD

**Issue by CubeGame** [ajbura/cinny#747] opened 2022-08-12 17:23 UTC
### Describe the bug

Opening the emoji menu in general settings causes cinny to turn into a blank screen with only the background.

Here is a screenshot of the console when this happens:
![image](https://user-images.githubusercontent.com/44947101/184411749-e9f89d8e-e01b-4c3d-92f5-a6a59362acd2.png)

### Reproduction

1. Enter general settings
2. Press Emoji

### Platform and versions

```shell
1. OS: Arch Linux
2. Browser: Chromium 103.0.5060.114
3. Cinny Version: v2.1.2
4. Matrix homeserver: matrix.org
```

### Additional context

I tried this both before and after globally adding an emoji pack.

**Comment by williamkray** [comment] 2022-08-12 23:15
check your account data for im.ponies objects, or state objects for any rooms you may be in for custom emojis... if the json is malformed cinny will crash _hard_. i had to clear out my account_data `im.ponies.user_emotes` entirely and set it to `{"images": {}, "pack": {}}` to resolve the issue.

**Comment by kfiven** [comment] 2022-08-13 02:28
@CubeGame Which client you used to add emoji in your account?

**Comment by CubeGame** [comment] 2022-08-13 10:10
@williamkray That fixed it
@kfiven Here I added an emoji pack in Cinny, but I forgot I also had added custom emoji with fluffychat a while ago.

**Comment by kfiven** [comment] 2022-08-13 10:15
Could you please provide the `prev_content` of im.ponies event in your account data? I tried to reproduce it but couldn't.

**Comment by CubeGame** [comment] 2022-08-13 10:32
@kfiven how can I get the `prev_content`?

**Comment by kfiven** [comment] 2022-08-13 10:38
@CubeGame 
* open element, 
* open the room in which it was happening, 
* click room name > developer tools
* `Explore room state`
* if it was personal emoji then `Explore account data`

**Comment by CubeGame** [comment] 2022-08-13 10:54
@kfiven I couldn't find `prev_content`, but I was able to reproduce the issue using an old version of fluffychat, which made the following account data for `im.ponies.user_emotes`:

```
{
  "type": "im.ponies.user_emotes",
  "content": {
    "emoticons": {
      ":cinnytest:": {
        "url": "mxc://matrix.org/gjfLAJNbqxlYSpEFXuPbAPra"
      }
    }
  }
}
```

I think the problem causing Cinny to crash is the old Fluffychat put `emoticons` instead of `images`.

**Comment by kfiven** [comment] 2022-08-13 10:57
Thanks! btw which version of fluffy was it?

**Comment by kfiven** [comment] 2022-08-13 11:08
Looks like in early days fluffy implemented [this version](https://github.com/Sorunome/matrix-doc/blob/b41c091dce3c29b3ade749f18d3350597a567512/proposals/2545-emotes.md) of msc2545

**Comment by CubeGame** [comment] 2022-08-13 11:10
I think `0.31.3` although in-app it said Unknown.

I looked at the history of [MSC2545](https://github.com/matrix-org/matrix-spec-proposals/pull/2545), and it is changed from `short` to `emoticons` [on 24 Sep 2020](https://github.com/Sorunome/matrix-doc/blob/72b21746dccf45d02ed7ca85d118293ee04096be/proposals/2545-emotes.md#user-emoticons), which was changed to `images` [on 25 Mar 2021](https://github.com/Sorunome/matrix-doc/blob/4f6d14724a0440ae060aa84727792e3acc7a3f9f/proposals/2545-emotes.md#example-image-pack-event).

[Also see the Unstable prefix section](https://github.com/Sorunome/matrix-doc/blob/soru/emotes/proposals/2545-emotes.md#unstable-prefix).

**Comment by kfiven** [comment] 2022-08-13 11:13
Well then not a Cinny issue, so I am closing this one.

**Closed as not planned by kfiven** 2022-08-13 11:13 UTC
