### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by PoneyClairDeLune** [ajbura/cinny#1610] opened 2023-12-26 16:53 UTC
### Describe the problem

Please consider adding translations in other languages. This would help Cinny serve a wider audience who don't speak English at all.

### Describe the solution you'd like

1. Format the strings to allow internationalization
2. Allow translators to directly submit translation files

### Alternatives considered

There is no alternative method.

**Comment by aceArt-GmbH** [comment] 2023-12-26 20:17
duplicate of #164.
See #681 and #1576 for work on this issue

**Closed as not planned** 2023-12-26 21:14 UTC
