### ISSUE TITLE
New messages don't appear

### ISSUE THREAD

**Issue by Salamandar** [ajbura/cinny#185] opened 2021-12-16 14:27 UTC
#### Describe the bug

Sometimes, new messages don't appear at the bottom of the feed. Once this happens, no new messages appear and you need to reload the page or go to another channel.
The left panel is updated correctly (white dot for unread message, and notification count).

#### To Reproduce
* Receive a message… ?

#### Expected behavior
Messages appear at the bottom of the messages view.

#### Desktop (please complete the following information):
 - OS: Linux
 - Browser: Firefox 95
 - Version: 1.6.0

**Comment by ajbura** [comment] 2021-12-16 15:11
@Salamandar anything unusual in console? Also are you sure there was new message and not any other events (join/leave/ban etc)?

**Comment by Salamandar** [comment] 2021-12-16 18:29
> Also are you sure there was new message and not any other events (join/leave/ban etc)?

Yeah because sometimes when I send a message it doesn't appear :)

And for the console, I wait for the bug to reappear and to not press ctrl-r out of muscular memory.

**Comment by Salamandar** [comment] 2021-12-17 14:22
Does this look interesting to you ?
```
Uncaught TypeError: n.path is undefined
    xp https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    qe https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Ze https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Sr https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Sr https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Mr https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Or https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Le https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Or https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Or https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Qt https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Yt https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    unstable_runWithPriority https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Vo https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Re https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Jt https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
main.cdc88e4d50c0e2a98e4d.bundle.js:2:441815
    xp https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    qe https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Ze https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Sr https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Sr https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Mr https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Or https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Le https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Or https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Or https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Qt https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Yt https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    bind_applyFunctionN self-hosted:1376
    Yt self-hosted:1339
    unstable_runWithPriority https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Vo https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Re https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    Jt https://cinny.salamandar.fr/main.cdc88e4d50c0e2a98e4d.bundle.js:2
    bind_applyFunctionN self-hosted:1376
    Jt self-hosted:1339

```

**Comment by ajbura** [comment] 2021-12-17 14:30
Was there any spoiler in timeline when this error appeared or you clicked on spoiler?

**Comment by Salamandar** [comment] 2021-12-18 20:03
Nope, no spoiler. Most people in this room are accessing it through IRC, so there's no advanced "features" in use.

**Comment by ajbura** [comment] 2021-12-26 05:59
The error has been fixed in 7c368ae0297285a8a6daf55353b5533796a1315b but have no idea this fixes the original issue.

**Comment by viasux** [comment] 2022-02-18 14:50
> The error has been fixed in [7c368ae](https://github.com/ajbura/cinny/commit/7c368ae0297285a8a6daf55353b5533796a1315b) but have no idea this fixes the original issue.

I experience this too!

**Comment by viasux** [comment] 2022-03-08 20:27
This appears to be much worse in v1.8.0, probably a firefox browser based issue.

Also my issue includes sending messages.

**Comment by kfiven** [comment] 2022-03-09 13:01
For reproducing:

Use firefox, try sending a multiline message. (Others also reported to happen on single line msg but we are not able to reproduce that for now).

**Comment by kfiven** [comment] 2022-03-16 04:22
Get a notification > Open room via that and when you send message they don't appear.

Another one reproducible.

**Closed as completed** 2022-03-17 02:46 UTC
Labels: type: bug
