### ISSUE TITLE
[Feature] Move private chats to the top when you receive/send a new message

### ISSUE THREAD

**Issue by Litom** [ajbura/cinny#304] opened 2022-02-05 17:23 UTC
#### Is your feature request related to a problem? Please describe.
It is hard for me to find the DM channel where a message was sent to me. Especially if I have many private chats open or write with one person often and then the chat is still displayed relatively far down.

#### Describe the solution you'd like
Move the specific direct message channel inside the "People" section to the top if you receive a message or write a message in this channel.
Optionally: Allow to pin direct message channels to the top (always staying in the same position above other channels in the list, like e.g. telegram does it)

#### Additional context
![solution](https://user-images.githubusercontent.com/18378982/152651963-21f49b48-5580-4221-9a4a-bcfdff070aed.png)

**Comment by kfiven** [comment] 2022-03-09 09:26
Duplicate of #54

**Closed by kfiven** 2022-03-09 09:26 UTC
