### ISSUE TITLE
Allow changing of time and date formats

### ISSUE THREAD

**Issue by imbev** [ajbura/cinny#635] opened 2022-06-19 18:20 UTC
### Describe the problem

Currently, dates are formatted as DD/MM/YYYY, such as `18/06/2022`.

I prefer for time to be formatted as YYYY-MM-DD, such as `2022-06-19`

### Describe the solution you'd like

I would like an option, (probably under appearance settings) to change the default date format.

**Comment by kfiven** [comment] 2022-06-20 01:42
Duplicate of #60

**Closed as not planned by kfiven** 2022-06-20 01:42 UTC
