### ISSUE TITLE
Account switcher

### ISSUE THREAD

**Issue by Maxb0tbeep** [ajbura/cinny#1245] opened 2023-05-22 05:25 UTC
### Describe the problem

I have more than one matrix account and its annoying to log out and sign in to each one

### Describe the solution you'd like

an account switcher menu similar to discord

### Alternatives considered

using cinny as both a desktop and web app

**Comment by kfiven** [comment] 2023-05-22 10:30
Duplicate of #66

**Closed as completed by kfiven** 2023-05-22 10:30 UTC
