### ISSUE TITLE
Remember last open room per space

### ISSUE THREAD

**Issue by MartijnBraam** [ajbura/cinny#671] opened 2022-07-11 15:40 UTC
### Describe the problem

When switching between spaces in the leftmost column the room that was open stays open at the moment. 

### Describe the solution you'd like

I like the discord behavior more where every top-level space remembers which room was open in it so when clicking a space it also switches to the last open room in it. This makes switching between two rooms in two spaces way quicker (one click to switch instead of clicking twice)

**Comment by kfiven** [comment] 2022-07-12 06:11
duplicate of #353

**Closed as not planned by kfiven** 2022-07-12 06:11 UTC
