### ISSUE TITLE
Display name and profile pictiure not loading sometimes

### ISSUE THREAD

**Issue by Miepee** [ajbura/cinny#610] opened 2022-06-06 12:33 UTC
### Describe the bug

Sometimes, the display names and profile pictures/avatars of other users aren't showing, but instead their mxid (@user:homeserver) and a blank profile picture.
This only is buggy in the timeline, clicking on a user shows their proper display name + pfp.
Timeline in cinny:  
![image](https://user-images.githubusercontent.com/38186597/172161182-b46a5284-0282-4917-949f-6bfd20bbc21e.png)
User view:
![image](https://user-images.githubusercontent.com/38186597/172161252-63276cec-fb6c-4a67-99ba-4a40f59e4ddc.png)

### Reproduction

Sadly I do not know how to reproduce. It just happens sometimes.

### Expected behavior

Profile pictures and display names should properly show.

### Platform and versions

```shell
1. OS: Windows 10 21H1
2. Browser: Firefox 99.0.1
3. Cinny version: 2.0.4 (app.cinny.in)
4. Matrix homeserver: Me: matrix.org; other users: t2bot.io, matrix.org; rooms: matrix.org, kde.org
```

### Additional context

Other clients do not have such issues.

**Comment by kfiven** [comment] 2022-06-07 06:02
Duplicate of #98

**Closed as completed by kfiven** 2022-06-07 06:02 UTC
