### ISSUE TITLE
Allow configuring 12/24h format for timestamps

### ISSUE THREAD

**Issue by ghost** [ajbura/cinny#1549] opened 2023-11-13 21:34 UTC
### Describe the problem

cinny always display message timestamps in a 12h format (using `hh` formatter in https://github.com/cinnyapp/cinny/blob/dev/src/app/utils/time.ts#L12).

### Describe the solution you'd like

It would be nice to be able to specify if time should be formatted on 12h (`hh`) or 24h (`HH`).

**Comment by kfiven** [comment] 2023-11-13 22:35
Duplicate of #60

**Closed as completed by kfiven** 2023-11-13 22:35 UTC
