### ISSUE TITLE
Private rooms in Spaces are displayed as Unknown rooms

### ISSUE THREAD

**Issue by EntityinArray** [ajbura/cinny#1897] opened 2024-08-14 20:06 UTC
### Describe the bug

CInny shows Private rooms in Spaces as Unknown rooms that you cannot join
![image](https://github.com/user-attachments/assets/3ca2dbed-831f-469e-b7ea-a3764faa585f)

### Reproduction

1. Go to a Space (for example: https://matrix.to/#/#rossmannrepair:matrix.org)
2. Notice Unknown private rooms

### Expected behavior

Private rooms are not displayed

### Platform and versions

```shell
1. OS Windows 10
2. Browser Chrome 127.0.6533.119
3. Cinny v4.1.0
4. Matrix homeserver isekai.su
```

**Comment by SiwonP** [comment] 2024-09-26 17:15
I experienced the same bug but also for not private rooms I have not yet joined. 
I looked into the HTTP request and found out that requests
```
GET /_matrix/client/v1/rooms/{roomId}/hierarchy 
```
when roomId is the actual of the **room** return a 403 M_UNAUTHORIZED. 

Compared to Element, I see the name and thumbnail of the unjoined rooms. 

Hence, I tried to call 
```
GET /_matrix/client/v1/rooms/{roomId}/hierarchy 
```
Where roomId is the id of the **space**, and it worked : I got the list of rooms with their names and thumbnails and so on.

I wonder if calling the hierarchy for each room is the way to go. 

Anyway, I would gladly volunteer to discuss and implement a patch for this !

Thanks

**Comment by williamkray** [comment] 2024-09-26 20:53
indeed, all of this is related to https://github.com/cinnyapp/cinny/issues/1846 as well, and discussion with the developers in their matrix room has indicated that this is exactly why it's not working. the spec does not define what that endpoint should return when executed against a non-space room, and conduit apparently returns content properly, which has led the developers to believe that this is a reasonable use of the endpoint despite it not working on synapse, which is probably the most common matrix server implementation in the wild.

the developers have shared that they are working with the synapse team and submitting PRs upstream to attempt to resolve this at the synapse level, which is a significantly slower process and may or may not have success, rather than simply changing their own code's logic to use the appropriate room discovery mechanisms.

**Comment by kfiven** [comment] 2024-09-27 12:01
I have repeated this many times but it's a bug in syanpse and instead of building around it we are trying to fix it. Synapse return valid response if room id is local room but if the room is over federation the bug hits. Anyways as this is duplicate of #1846, I am closing it and the progress on it can be tracked on https://github.com/element-hq/synapse/pull/17750

**Closed as not planned by kfiven** 2024-09-27 12:01 UTC
