### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by pbk123461** [ajbura/cinny#1939] opened 2024-09-09 16:21 UTC
### Describe the bug

when ever I send an image or receive an image, I can't see it in cinny, it says retry but when I click it nothing happens
![image](https://github.com/user-attachments/assets/72b040a1-2298-47ac-8d6d-19efc3e839ee)

### Reproduction

just sending an image on an encrypted or non encrypted room

### Expected behavior

i wanted it to show me the sent or received image

### Platform and versions

```shell
1. OS: Chrome OS 121
2. Browser: Chrome 121
3. CinnyVersion: V4.1.0
4. MatrixHomeserver: Matrix.org
5. Matrix Room Version: 11
```

### Additional context

it works on other clients but doesnt work on cinny

**Comment by kfiven** [comment] 2024-09-09 23:52
duplicate of #1818

**Closed as not planned by kfiven** 2024-09-09 23:52 UTC

**Comment by Luciogi** [comment] 2024-09-16 19:18
I was facing same issue on 4.2.0,  4.2.1.
I deleted `~/.cache/cinny`

Now images loads fine
