### ISSUE TITLE
Line breaks seem to get lost along the way

### ISSUE THREAD

**Issue by grandeljay** [ajbura/cinny#584] opened 2022-05-27 08:55 UTC
### Describe the bug

When writing multiple paragraphs in cinny, the empty ones are removed, making the text harder to read.

## Test 1

Write the following message in **cinny**:
```
Hello World
This is a test

There should be a line break above this
```

The output is as follows
| Cinny | Element |
| ------ | -------- |
| <pre>Hello World<br />This is a test<br />There should be a line break above this</pre> | <pre>Hello World This is a test<br /><br />There should be a line break above this</pre> |

## Test 2

Write the following message in **element**:
```
Hello World
This is a test

There should be a line break above this
```

The output is as follows
| Cinny | Element |
| ------ | -------- |
| <pre>Hello World<br />This is a test<br /><br />There should be a line break above this</pre> | <pre>Hello World<br />This is a test<br /><br />There should be a line break above this</pre> |

### Expected behavior

I expect the line breaks to be the same way as they were during message creation (before sending)

### Platform and versions

```shell
OS: Windows 10
Browser: LibreWolf (Firefox) v100.0-3
Cinny: v2.0.3
Homeserver: matrix.org
```

### Additional context

I think I have an option enabled to send message in markdown.

**Comment by kfiven** [comment] 2022-05-27 09:01
Why this happens is really well explained by @samueldr in #174 and seems duplicate of #193.

**Closed as completed by kfiven** 2022-05-27 09:01 UTC
