### ISSUE TITLE
Icon on system tray

### ISSUE THREAD

**Issue by LeviLeal** [ajbura/cinny#1146] opened 2023-03-01 06:39 UTC
### Describe the problem

Once cinny is closed, you will need to reopen it from the menu again.

### Describe the solution you'd like

Create a icon on the system tray to open cinny again.

**Comment by kfiven** [comment] 2023-03-01 07:33
duplicate of https://github.com/cinnyapp/cinny-desktop/issues/65

**Closed as completed by kfiven** 2023-03-01 07:33 UTC
