### ISSUE TITLE
Read receipts not discoverable

### ISSUE THREAD

**Issue by reesericci** [ajbura/cinny#633] opened 2022-06-17 04:04 UTC
As a new user coming from Element, it was quite difficult to find the read receipts functionality. I didn't know that I had to click the dropdown menu to view them; in every other chat app I've used, the read receipts are shown right next to the message.

I'm proposing showing the little icons next to the message block, just like Element. When clicked, it will show the same popup as in the current implementation.

Thanks!

--reese

**Comment by kfiven** [comment] 2022-06-17 15:05
Looks like a duplicate of #588 or are you requesting something different?

**Comment by reesericci** [comment] 2022-06-17 16:16
You're right, it's a duplicate. I only searched for read receipts when looking for duplicate issues.

--reese

**Closed as not planned** 2022-06-17 16:16 UTC
