### ISSUE TITLE
A tray icon

### ISSUE THREAD

**Issue by Kommynct** [ajbura/cinny#1114] opened 2023-02-07 21:26 UTC
### Describe the problem

I close out of cinny and it's just gone, instead of in the background

### Describe the solution you'd like

An SNI dbus tray icon

### Alternatives considered

I don't think this really applies here, it's very standard for messengers, not having one is rather cumbersome

### Additional context

I use sway with waybar in case there is supposed to be one, I haven't found one in either arch or alpine.

**Comment by kfiven** [comment] 2023-02-07 23:22
Duplicate of https://github.com/cinnyapp/cinny-desktop/issues/65

**Closed as completed by kfiven** 2023-02-07 23:22 UTC
