### ISSUE TITLE
Images aren't loading

### ISSUE THREAD

**Issue by idklol725** [ajbura/cinny#1929] opened 2024-09-06 11:17 UTC
### Describe the bug

when i send a screenshot or if my friend sents me an img it just says retry and neither me or my friend can see the message, but it img sent in cinny chat so plz fix this issue

### Platform and versions

```shell
1. OS = ChromeOS 121
2. Browser = Chrome 121
3. Cinny version = 4.1.0
4. Homeserver = Matrix.org
```

**Comment by kfiven** [comment] 2024-09-06 11:34
Duplicate of #1818

**Closed as not planned** 2024-09-06 11:35 UTC
