### ISSUE TITLE
Commands (slash and go-to) complete and activate anywhere in the input

### ISSUE THREAD

**Issue by samueldr** [ajbura/cinny#155] opened 2021-11-06 20:29 UTC
#### Describe the bug

I'm not sure if it's a design decision or a bug, but the behaviour is surprising and may lead to "fun" problems for some users.

The inputs for go-to commands are less likely to cause issues, but I assume if this is a bug, there is a bug for them too.

#### To Reproduce

1. In a room (or DM)
2. Type and send `To activate markdown mode, type /markdown` as if to reply to a question
3. Observe the input eating `/markdown` and the command being applied

Think about the more destructive: `The command to leave a room is /leave`.

#### Expected behavior

Command input should be anchored to the start of the input box. Only "text content" completion should be anchored at any points.

#### Screenshots

N/A

#### Desktop (please complete the following information):

 - OS: NixOS Linux
 - Browser: Chrome 
 - Version: Not important
 
Cinny

 - 1.4.0

#### Additional context

See #156

**Comment by kfiven** [comment] 2021-11-07 01:43
Duplicate of #65

**Closed as completed** 2021-11-07 04:32 UTC

**Comment by samueldr** [comment] 2021-11-07 04:40
Oh, didn't see that one while searching sorry!
