### ISSUE TITLE
Emoji picker does not automatically get selected

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#239] opened 2022-01-16 04:49 UTC
#### Describe the bug
When you click an emoji for reaction, then start typing, it does not correctly search in the emoji picker, instead it types in the text dialogue. (better explained from video)

#### To Reproduce
1. Click the reaction button
2. Start typing

#### Expected behavior
Expected to start searching in the emoji picker

#### Screenshots
https://user-images.githubusercontent.com/47131867/149647661-f7295ad6-ed56-4e51-aae9-3a390dfd1680.mp4

#### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Librewolf
 - Version: 1.6.1

**Comment by kfiven** [comment] 2022-01-21 03:00
Duplicate of #62

**Closed as completed by kfiven** 2022-01-21 03:00 UTC
