### ISSUE TITLE
Verifying Sessions and Managing room features

### ISSUE THREAD

**Issue by Sehrail** [ajbura/cinny#180] opened 2021-12-07 18:50 UTC
Cinny needs verifying sessions and managing rooms. When im use cinny, element user sees me untrusted session and sometimes element users cant see my encrypted messages because ım untrusted session. thats irritating. I can't manage my rooms with cinny because cinny doesn't have managing room features. I think cinny will be the best client if these issues are resolved

**Comment by kfiven** [comment] 2021-12-08 01:51
Duplicate of #3 and #11

**Comment by kfiven** [comment] 2021-12-08 01:53
There a workaround to verify session which is explained at https://github.com/ajbura/cinny/issues/11#issuecomment-973943553 

> To verify the session go to your profile in element in any room and click on unverified sessions, then click manual verify. You can see Cinny session details in Cinny’s settings (just to be sure when manually confirming). This is a workaround until we have emoji verification.

**Closed as completed** 2021-12-13 11:51 UTC
