### ISSUE TITLE
Cinny defaults to matrix.org, no way to change it

### ISSUE THREAD

**Issue by samip5** [ajbura/cinny#145] opened 2021-10-24 00:39 UTC
#### Describe the bug
It should default to the $HOST header or have env variable or configuration option to set it to something else.

#### To Reproduce
1. Deploy Cinny container with reverse proxy
2. Go to Cinny
3. See it default to matrix.org

#### Expected behavior
It would default to $HOST.

#### Screenshots

![image](https://user-images.githubusercontent.com/1703002/138575515-f4dbf098-50a3-4753-b901-88a32368abd3.png)

**Comment by ajbura** [comment] 2021-10-24 02:34
Duplicate of #64

**Closed as completed** 2021-10-24 02:35 UTC
