### ISSUE TITLE
Secure Backup Key not working

### ISSUE THREAD

**Issue by Sehrail** [ajbura/cinny#834] opened 2022-09-09 17:37 UTC
### Describe the bug

With the v2.0.0 update, Cinny received the session authentication feature with the Secure Backup Key. When we authenticate our session using the Secure Backup Key after logging in with cinny from a new location, cinny does not transfer the encryption keys. Therefore, it is necessary to manually transfer the encryption keys to the new session.

### Platform and versions

```shell
1. fedora 36
2. Brave 1.43.89
3. Cinny v2.1.3
4. tchncs.de
```

**Comment by kfiven** [comment] 2022-09-10 03:13
duplicate of #792

**Closed as not planned by kfiven** 2022-09-10 03:13 UTC
