### ISSUE TITLE
Room navigation using back/forward buttons

### ISSUE THREAD

**Issue by vurpo** [ajbura/cinny#685] opened 2022-07-15 23:07 UTC
### Describe the problem

Pressing the back or forward buttons in the browser takes me away from Cinny, instead of browsing through my recently viewed rooms. I'm used to having the ability to browse through rooms this way for example in Element Web and Discord.

### Describe the solution you'd like

To introduce room history in the browser (and also in the desktop app for e.g. users who have back and forward buttons on their mouse or keyboard), you can use JS to add the current room ID to the current browser URL, use `history.pushState` to add the address to the browser history, add a listener for `popstate` to react to browser history changes and change the app state instead of navigating away from the page (if the URL stays within the Cinny app), and on startup read the room ID from the URL to open the corresponding room directly. This is the way that other web-based apps, such as the ones I mentioned, implement it.

**Comment by kfiven** [comment] 2022-07-17 05:10
duplicate of #158

**Closed as not planned by kfiven** 2022-07-17 05:10 UTC
