### ISSUE TITLE
Form breaks when attaching a large file

### ISSUE THREAD

**Issue by kok42** [ajbura/cinny#1027] opened 2022-12-19 15:00 UTC
### Describe the bug

When uploading a large file as attachment from freezes; no other files can be attached; attached file cannot be removed; messages are sent without attachment. 
Tested with a 10GB mp4 video.

### Reproduction

1. Go to any chatroom
2. Attach large file

### Expected behavior

Expected an error message or progress of uploading visible. Expected attachmet to be removable  

### Platform and versions

```shell
1. Windows 10
2. Opera GX
3. app.cinny.in
4. martix.org
```

**Comment by kfiven** [comment] 2022-12-19 15:54
duplicate of #983

**Closed as completed by kfiven** 2022-12-19 15:54 UTC
