### ISSUE TITLE
spoilers are revealed in replies

### ISSUE THREAD

**Issue by 2-www** [ajbura/cinny#985] opened 2022-11-19 17:00 UTC
### Describe the bug

spoilers are displayed in cleartext in the line that shows the parent message

### Reproduction

1. reply to a spoilered message

### Expected behavior

spoiler is hidden

### Platform and versions

```shell
dev.cinny.in (19/11/2022) on epiphany
```

**Comment by viasux** [comment] 2022-11-19 19:29
Just noticed this as well on Cinny v2.2.2 / im.kitties.gay / librewolf

**Comment by ajbura** [comment] 2022-11-20 08:27
duplicate of #189

**Closed as completed by ajbura** 2022-11-20 08:27 UTC

**Comment by 2-www** [comment] 2022-11-20 15:33
@ajbura please re-close this as not completed but duplicate
