### ISSUE TITLE
Adding Custom Emotes

### ISSUE THREAD

**Issue by Sehrail** [ajbura/cinny#628] opened 2022-06-14 16:01 UTC
### Describe the problem

We can use custom emotes with cinny but we can't add custom emotes with cinny. We also need FluffyChat like client for adding custom emotes. I think cinny needs custom emote adding support

**Comment by kfiven** [comment] 2022-06-14 16:03
Duplicate of #83

**Closed as not planned by kfiven** 2022-06-14 16:03 UTC
