### ISSUE TITLE
Allow Space maintainers set custom ordering of rooms in spaces

### ISSUE THREAD

**Issue by Reinachan** [ajbura/cinny#903] opened 2022-10-10 17:17 UTC
### Describe the problem

Currently spaces with a lot of rooms can quickly get really disorganised as they're ordered alphabetically. While putting things into subspaces does help a littlebit, it's still far from ideal, to the point where I've had to name rooms or spaces with a specific letter in front of it so that it would appear further down.

### Describe the solution you'd like

Implement the [m.space.child relationship from the Matrix spec](https://spec.matrix.org/v1.3/client-server-api/#ordering-1) and allow for restructuring using the `content -> order` key. This key is a string separate from the name which is used for lexical ordering. Ideally this should be handled as simply as allowing for drag and drop. each space.child can be given a number as its order for simplicity.

### Alternatives considered

Instead of drag and drop, allow for manual assignment of the order key. This can for example be added to "manage rooms" modal next to the "open" button.

### Additional context

Link to relevant spec
https://spec.matrix.org/v1.3/client-server-api/#ordering-1

**Comment by Reinachan** [comment] 2022-10-10 17:43
I realise that drag and drop can be pretty complicated to implement as it introduces a lot of additional concerns like, what if you move a room into another space? As this is functionality I'd consider pretty important for making a strong first impression to new users when they join a space, I would suggest that you consider doing the alternative method as an intitial method of handling this and potentially switch or enable drag-and-drop in the future.

**Comment by kfiven** [comment] 2022-10-12 03:50
Marking Duplicate of #722 

Closing #722 as this one is well written.

**Comment by ajbura** [comment] 2024-07-26 17:19
this has been added in v4.0.0

**Closed as completed by ajbura** 2024-07-26 17:19 UTC
Labels: type: improvement, area: room-list
