### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by Saiv46** [ajbura/cinny#172] opened 2021-11-29 05:13 UTC
#### Is your feature request related to a problem? Please describe.
Cinny currently lacks offline support and proper caching, which may slow down loading.

#### Describe the solution you'd like
Add service worker that will handle caching, offline support, pushes and other features in future.

#### Describe alternatives you've considered
- Removing `fontshare.com` CSS (that's for another PR)
- Implementing cache in IndexedDB

**Comment by ajbura** [comment] 2021-12-01 10:15
Duplicate of #17

**Closed as completed** 2021-12-13 11:52 UTC

**Comment by Silther** [comment] 2023-08-06 15:18
@kfiven 
Can a PWA change the colour of the android statusbar?
