### ISSUE TITLE
firefox mobile PWA error

### ISSUE THREAD

**Issue by Silther** [ajbura/cinny#1375] opened 2023-08-06 13:27 UTC
### Describe the bug

App cannot be installed as a PWA with Firefox mobile (the only working mobile browser for me).
more precisely, the app is only added as a shortcut to the home screen and the search bar does not disappear (PWA from Instagram works in Firefox Mobile without problems)

### Reproduction

use cinny web on firefox mobile
add to homescreen via menu

1. click on the new homescreen shortcut

### Platform and versions

```shell
1. Android 13
2. Firefox Mobile
3. Cinny web
4. matrix.org
```

**Comment by kfiven** [comment] 2023-08-06 14:16
Duplicate of #17

**Closed as not planned by kfiven** 2023-08-06 14:16 UTC
