### ISSUE TITLE
Code Blocks no Longer Render?

### ISSUE THREAD

**Issue by Capital-EX** [ajbura/cinny#1473] opened 2023-10-21 18:02 UTC
### Describe the bug

When using markdown formating, code blocks will no long be correctly registered. This had been working previous.

### Reproduction

1. Enable markdown
2. Attempt to create a code block using triple back ticks
3. It fails to create a code block

### Expected behavior

![Screenshot_20231021_134514](https://github.com/cinnyapp/cinny/assets/13488718/2267ea09-7fee-49f0-b949-c2febe598fd0)

### Platform and versions

```shell
1. OS: Arch Linux
2. Browser: Firefox 118.0.2 (64-bit)
3. Cinny version: 3.0.0
4. Matrix homeserver: envs.net
```

**Comment by neptuwunium** [comment] 2023-10-21 20:22
Code blocks (and similarly, block quotes) are containers, not inline markdown statements (which is what the option is called in the settings.)

Markdown as a whole is broken as Cinny now only lets you use inline markdown, which is confusing because the WYSIWYG does let you use containers. Anything that is considered a container or similar is broken (1. lists, # headings, etc).

**Comment by daemonspring** [comment] 2023-10-22 00:22
FYI the devs had plenty of feedback prior to releasing the latest version that stuff like this was going to happen and it was going to cause problems for people. Literal months of various people asking about whether markdown was still going to be supported and indicating that they wanted it. I gave up on feedback because the responses showed a trend of seeming selective about replies or if there was a response, dismissing the concern in baffling ways, or saying markdown is supported but obviously not addressing the fact it isn't fully supported. It was as if there was a deliberate attempt to misunderstand feedback. Or like that particular feedback was not appreciated. I never felt like a clear answer was actually given. I can't describe it any better because it was so bizarre. It just gave me a weird feeling.

I still can't fathom why this update was approached as it was. The attitude seems to be that people will just get used to it, but personally I'll just be using Element again for now because markdown was a core part of how I used the application (see #1305). As unsatisfying as Element's UI is compared to Cinny, my primary interaction is the text editor anyway. Unfortunately, markdown is a critical feature for me.

Why release an update with a known regression in a fundamental part of the application? If the plan is to fully support markdown, it makes no sense to release before then and break support and cause predictable problems for users. To me, this indicates a deeper problem with the development and feedback process.

I'd just like to be clear: **I don't expect my personal usage of chat clients to count for much**. What concerns me is **how** feedback and communication was handled. If you're going to regress on a feature, don't play semantics about it and acknowledge that you know it will cause problems for certain users and you're choosing to do it anyway. Acting like only supporting inline markdown is still markdown support is just disingenuous. It was clear from months of chat that no one who wanted markdown support was going to be happy with partial support, so why act like it isn't what it is?

I'm leaving my feedback here in case anyone else can see the pattern I do and is wondering if they're going insane. You're not.

**Comment by kfiven** [comment] 2023-10-22 00:56
@daemonspring You need to understand that this is a volunteer driven project. If you think something is broken you are more than welcome to contribute.

As about the feedback we've explained it from the start, mixing both markdown and WYSIWYG caused issues that were far worse than having inline markdown optional and fully functional WYSIWYG. 

It is the result of the feedback that we've been able to figure out the inline markdown.

And calling the devs selective is as absurd as it sounds. As I already said, it's volunteer driven project a lot of questions/replies gets missed because people have real life as well, but I always try to answer people as much I can. 

You also need to understand that you need to stop repeating the same response everywhere with this passive aggressive approach without looking at previous discussion and start calling people selective without any credible evidence.

**Comment by neptuwunium** [comment] 2023-10-22 03:19
Can you please cite the discussions/issues where 

> mixing both markdown and WYSIWYG caused issues that were far worse than having inline markdown optional and fully functional WYSIWYG. It is the result of the feedback that we've been able to figure out the inline markdown.

was discussed, because I do not understand how a WYSIWYG which has all of the features of common markdown (+ spoilers)  would cause issues with markdown itself, and I am not well versed with the Cinny codebase to confidently say if it should be possible at all.

In other words, I do not understand how a new input system can be such a complex design that it's not possible for the WYSIWYG editor to translate it's input back into markdown rather than plain html (or indeed, translate html back into markdown, which [dependencies do exist for](https://www.npmjs.com/package/turndown)). Or more realistically, why ~~old markdown renderer couldn't be fallen back to for non-WYSIWYG as they should be two separate input methods?~~ the WYSIWYG control bar doesn't revert back to normal markdown when it's disabled.

Edit: I just now realized that toggling WYSIWYG does not actually reset the state (which in my opinion is a weird choice as realistically very few people will click `Aa`, do some WYSIWYG and click it again.)

**Comment by williamkray** [comment] 2023-10-22 04:26
This is a duplicate of https://github.com/cinnyapp/cinny/issues/1452 but seems to have more engagement... Although I don't know how productive it is.

**Comment by daemonspring** [comment] 2023-10-22 06:15
@kfiven 
> You also need to understand that you need to stop repeating the same response everywhere with this passive aggressive approach without looking at previous discussion and start calling people selective without any credible evidence.

- Your response focusses on questioning my motives and implying entitlement in a passive aggressive way
- You exaggerate my behaviour to the same effect
- I have been in the chat for months, reading every post, which is why I have observed a pattern
- Anyone can read the chat if they want to and see what occurred

It's not possible to contribute the solution to a problem you can't successfully discuss, nor a problem that isn't even acknowledged as a problem.

I gave my response in chat as to why the technical reasons given for why markdown couldn't be fully supported don't make sense. It's hard to argue that no one saw my statements because I did receive replies and they were selective in what they addressed. So please go and gaslight someone else.

My frustration is real and genuine, whether you think it is reasonable or not. Regardless, I realise my continuing presence will not be productive, so I will no longer interact with this project.

**Comment by kfiven** [comment] 2023-10-22 07:17
@daemonspring Glad you realized that you are not being productive. I'd advise to learn some basics in engaging in foss project discussions.

Anyways I'm going to close this one as duplicate of #1452.

**Closed as completed by kfiven** 2023-10-22 07:17 UTC
