### ISSUE TITLE
Dollar signs cause weird formatting

### ISSUE THREAD

**Issue by bengaywins** [ajbura/cinny#804] opened 2022-09-01 04:07 UTC
### Describe the bug

If you use dollar signs in the desktop client, no matter what you type, it formats it weirdly. 

### Reproduction

1. Send a message in a room and have n+1 dollar signs.
2. See how it formats things unpredictably unless you escape them

### Expected behavior

No weird formatting

### Platform and versions

```shell
1. OS: Win11
2. Cinny Desktop
3. Cinny version: v2.1.2
```

**Comment by bengaywins** [comment] 2022-09-01 04:07
![image](https://user-images.githubusercontent.com/20360959/187829530-79626076-39f9-43ae-8d95-5f854bfa58d6.png)
This is an example screenshot created with the text: `$nothing to see here just $creating a screenshot`.

**Comment by kfiven** [comment] 2022-09-01 04:12
Duplicate of #709 which has been fixed but not landed in stable yet.

**Closed as not planned by kfiven** 2022-09-01 04:12 UTC

**Comment by bengaywins** [comment] 2022-09-01 04:36
@kfiven Any idea when a new release will contain it? And thank you!

**Comment by kfiven** [comment] 2022-09-01 10:28
@bengaywins well there's no exact date, but we have some input-related issues left to fix. Meanwhile, https://dev.cinny.in always has the latest commit builds and is a great place to test out stuff and provide feedback.
