### ISSUE TITLE
Ability to log in with full MXID in username box

### ISSUE THREAD

**Issue by ShadowJonathan** [ajbura/cinny#365] opened 2022-03-09 09:03 UTC
#### Is your feature request related to a problem? Please describe.
![image](https://user-images.githubusercontent.com/22740616/157408526-bc4dcbb1-cd73-4eec-bf13-37ec98bd8d50.png)

#### Describe the solution you'd like
If possible, i'd like the above to strip the MXID when i leave the box, set the right homeserver, and then set the username space to the actual username.

**Comment by kfiven** [comment] 2022-03-09 09:08
Duplicate of #187

**Closed as completed by kfiven** 2022-03-09 09:08 UTC
