### ISSUE TITLE
Cannot view media beyond timeline preview

### ISSUE THREAD

**Issue by daenney** [ajbura/cinny#534] opened 2022-05-09 16:12 UTC
### Describe the bug

In the desktop app, when media is published to a room, it's not possible to pop it open for a bigger view. The media element has a "open in new tab" option, but that doesn't work within the desktop app bundle.

### Reproduction

1. Open any room
2. Find media
3. Click on "open in new tab"

### Expected behavior

Modal shows up that allows the viewing of the asset.

### Platform and versions

```shell
1. OS: Linux
2. Cinny Desktop 2.0
```

**Comment by williamkray** [comment] 2022-08-09 21:22
i think this is a duplicate of https://github.com/cinnyapp/cinny/issues/5 ?

**Comment by daenney** [comment] 2022-08-09 21:35
Sort of. Right now in the desktop app it's not possible _at all_ to view the image in a bigger way, because the "open in new tab" functionality doesn't work in that context. The feature suggested in #5 works to resolve this case too, but the problem is different.

**Closed as completed** 2022-08-19 06:45 UTC
