### ISSUE TITLE
Cinny crashes entering toki.club into the login screen

### ISSUE THREAD

**Issue by sowelipililimute** [ajbura/cinny#1449] opened 2023-10-14 02:50 UTC
### Describe the bug

The app crashes (everything turns blank) when I enter `toki.club` into the screen

### Expected behavior

It does not crash and instead brings me to login screen

### Platform and versions

```shell
1. OS: Fedora
2. Browser: Firefox 117.0.1 (64-Bit)
3. Cinny Version: https://app.cinny.in
4. Matrix Homeserver: toki.club
```

**Comment by kfiven** [comment] 2023-10-15 11:14
Probably duplicate of #1369

**Closed as completed by kfiven** 2023-10-15 11:14 UTC
Labels: type: bug
