### ISSUE TITLE
Pinned events

### ISSUE THREAD

**Issue by nexy7574** [ajbura/cinny#2015] opened 2024-10-18 13:25 UTC
### Describe the problem

Cinny cannot currently view room pins. It can receive the room pins state event, but it does not do anything with it, and treats it as an unknown event.

### Describe the solution you'd like

It would be nice to be able to see the room's pinned events in Cinny. Many other clients support this functionality so it would be nice to have it in cinny too.

### Alternatives considered

None - I have to open another client in order to look at pins.

**Comment by kfiven** [comment] 2024-10-18 21:38
duplicate of #68

**Closed as not planned by kfiven** 2024-10-18 21:38 UTC
